export const REQUEST_CART_DATA = 'REQUEST_CART_DATA'
export const SHOW_CART_DATA = 'SHOW_CART_DATA'
export const FAILED_GET_CART_DATA = 'FAILED_GET_CART_DATA'
export const SUCCESS_CART_DATA = 'SUCCESS_CART_DATA'