export const REQUEST_COBA_DATA = 'REQUEST_COBA_DATA'
export const SHOW_COBA_DATA = 'SHOW_COBA_DATA'
export const FAILED_GET_COBA_DATA = 'FAILED_GET_COBA_DATA'
export const SUCCESS_COBA_DATA = 'SUCCESS_COBA_DATA'