export const REQUEST_DETAIL_DATA = 'REQUEST_DETAIL_DATA'
export const SHOW_DETAIL_DATA = 'SHOW_DETAIL_DATA'
export const FAILED_GET_DETAIL_DATA = 'FAILED_GET_DETAIL_DATA'
export const SUCCESS_DETAIL_DATA = 'SUCCESS_DETAIL_DATA'