export const REQUEST_MYPRODUCT_DATA = 'REQUEST_MYPRODUCT_DATA'
export const SHOW_MYPRODUCT_DATA = 'SHOW_MYPRODUCT_DATA'
export const FAILED_GET_MYPRODUCT_DATA = 'FAILED_GET_MYPRODUCT_DATA'
export const SUCCESS_MYPRODUCT_DATA = 'SUCCESS_MYPRODUCT_DATA'