export const REQUEST_PRODUCT_DATA = 'REQUEST_PRODUCT_DATA'
export const SHOW_PRODUCT_DATA = 'SHOW_PRODUCT_DATA'
export const FAILED_GET_PRODUCT_DATA = 'FAILED_GET_PRODUCT_DATA'
export const SUCCESS_PRODUCT_DATA = 'SUCCESS_PRODUCT_DATA'